services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kanastra_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kanastrapass
  web:
    build: .
    # command: >
    #   sh -c "python manage.py collectstatic --noinput &&
    #     python manage.py migrate &&
    #     gunicorn kanastra_test.wsgi:application --bind 0.0.0.0:8000"
    command: bash -c "python manage.py makemigrations kanastra && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=kanastra_test.settings
    stdin_open: true
    tty: true
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db



volumes:
  postgres_data:
  pgadmin_data: